apiVersion: v2
name: remark42
description: A Helm chart for Remark42 comment system

type: application

maintainers:
  - name: groundhog2k

version: 0.2.8

appVersion: "v1.8.1"

dependencies:
  - name: redis
    version: 0.4.8
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: redis.enabled
