{{- $fullname := include "nextcloud.fullname" . }}
{{- $labels := include "nextcloud.labels" . }}
{{- $environment := include "nextcloud.environment" . }}
{{- $apiVersion := .Capabilities.APIVersions -}}
{{- range $job := .Values.defaultCronJobs }}
{{- if $apiVersion.Has "batch/v1" }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ $fullname }}-{{ $job.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: {{ $job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with $.Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: {{ $.Chart.Name }}-{{ .name }}
              {{- with $.Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ $.Values.image.registry }}/{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ $fullname }}
              env:
                - name: NEXTCLOUD_DATA_DIR
                  value: /var/datavolume/data
                {{- $environment | nindent 16 }}
              {{- with $.Values.env }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              args:
                - /bin/sh
                - -c
                - {{ $job.command }}
              volumeMounts:
                - mountPath: /var/www/html
                  name: nextcloud-vol
                - mountPath: /var/datavolume
                  name: nextcloud-data-vol
                - mountPath: /tmp
                  name: tmp
                - mountPath: /var/run
                  name: run
              resources:
                {{- toYaml $job.resources | nindent 18 }}
          {{- if $job.nodeSelector -}}
          {{- with $job.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- else }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: tmp
              emptyDir: {}
            - name: run
              emptyDir: {}
            - name: nextcloud-vol
            {{- if $.Values.storage.nextcloud.persistentVolumeClaimName }}
              persistentVolumeClaim:
                claimName: {{ $.Values.storage.nextcloud.persistentVolumeClaimName }}
            {{- else }}
            {{- if $.Values.storage.nextcloud.requestedSize }}
              persistentVolumeClaim:
                claimName: {{ $fullname }}
            {{- else }}
              emptyDir: {}
            {{- end }}
            {{- end }}
            - name: nextcloud-data-vol
            {{- if $.Values.storage.nextcloudData.persistentVolumeClaimName }}
              persistentVolumeClaim:
                claimName: {{ $.Values.storage.nextcloudData.persistentVolumeClaimName }}
            {{- else }}
            {{- if $.Values.storage.nextcloudData.requestedSize }}
              persistentVolumeClaim:
                claimName: {{ $fullname }}-data
            {{- else }}
              emptyDir: {}
            {{- end }}
            {{- end }}
---
{{- end }}