apiVersion: v2
name: commento
description: A Helm chart for Commento on Kubernetes

type: application

maintainers:
  - name: groundhog2k

version: 0.1.25

appVersion: "v1.8.0"

dependencies:
  - name: postgres
    version: 0.2.17
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: postgres.enabled
