apiVersion: v2
name: valkey
description: A Helm chart for Valkey on Kubernetes

type: application

maintainers:
  - name: groundhog2k
    url: https://github.com/groundhog2k/helm-charts

keywords:
  - cache
  - valkey

icon: https://valkey.io/img/Valkey-logo.svg

# This is the chart version
version: "2.2.5"

# This is the version number of the application being deployed.
appVersion: "9.0.3"
