apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes metrics-server

type: application

maintainers:
  - name: groundhog2k

version: 2.12.4

appVersion: "v0.4.3"

keywords:
  - metrics-server
