apiVersion: v2
name: mariadb
description: A Helm chart for MariaDB on Kubernetes

type: application

# This is the chart version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: 10.4.14