apiVersion: v2
name: mariadb
description: A Helm chart for MariaDB on Kubernetes

type: application

maintainers:
  - name: groundhog2k
    url: https://github.com/groundhog2k/helm-charts

keywords:
  - database
  - mariadb

version: "4.3.4"

appVersion: "11.4.9"
icon: https://mariadb.com/wp-content/uploads/2019/11/mariadb-logo_black-transparent-600x150.png
