apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes

maintainers:
  - name: groundhog2k

type: application

# This is the chart version.
version: 0.4.1

# This is the version number of the application being deployed.
appVersion: "5.8.0-apache"

dependencies:
  - name: mariadb
    version: 0.2.14
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mariadb.enabled
