apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes

maintainers:
  - name: groundhog2k

type: application

# This is the chart version.
version: "0.8.0"

# This is the version number of the application being deployed.
appVersion: "6.2.0-apache"

dependencies:
  - name: mariadb
    version: "0.2.25"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mariadb.enabled
