apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: groundhog2k

version: "0.9.2"

appVersion: "6.1.2"

dependencies:
  - name: mongodb
    version: "0.6.8"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mongodb.enabled
