apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: groundhog2k

version: "0.5.7"

appVersion: "5.0.5"

dependencies:
  - name: mongodb
    version: "0.4.17"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mongodb.enabled
  - name: elasticsearch
    version: "0.1.106"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: elasticsearch.enabled
