apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: groundhog2k

version: 0.4.10

appVersion: "4.3.7-jre11"

dependencies:
  - name: mongodb
    version: 0.3.16
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mongodb.enabled
  - name: elasticsearch
    version: 0.1.106
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: elasticsearch.enabled
