apiVersion: v2
name: graylog
description: A Helm chart for Graylog on Kubernetes

type: application

maintainers:
  - name: groundhog2k

version: "0.7.11"

appVersion: "5.2.7"

dependencies:
  - name: mongodb
    version: "0.5.22"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: mongodb.enabled
