apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL on Kubernetes

type: application

maintainers:
  - name: groundhog2k
    url: https://github.com/groundhog2k/helm-charts

keywords:
  - database
  - postgres

version: "1.3.9"

appVersion: "15.15"
icon: https://www.postgresql.org/media/img/about/press/elephant64.png
