apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL on Kubernetes

type: application

# This is the chart version
version: 0.1.0

# This is the version number of the application being deployed. 
appVersion: "12.4"
