apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rabbitmq.fullname" . }}-config
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
data:
  options.conf: |+
    management_agent.disable_metrics_collector = {{ .Values.disableMetricsCollector }}
  rabbitmq.conf: |+
    # Common settings
    loopback_users.guest = false
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    ## Username
    default_user = CHANGE_ME
    default_pass = CHANGE_ME
    {{- if contains "rabbitmq_peer_discovery_k8s" .Values.plugins }}
    ## Clustering
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.{{ .Values.clusterDomain }}
    cluster_formation.k8s.address_type = {{ .Values.clustering.addressType }}
    cluster_formation.k8s.service_name = {{ template "rabbitmq.fullname" . }}-internal
    cluster_formation.k8s.hostname_suffix = .{{ template "rabbitmq.fullname" . }}-internal.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    queue_master_locator = min-masters
    {{- end }}    
    {{- if .Values.options.memoryHighWatermark.enabled }}
    ## Memory Threshold
    total_memory_available_override_value = {{ include "rabbitmq.toBytes" .Values.resources.limits.memory }}
    vm_memory_high_watermark.{{ .Values.options.memoryHighWatermark.type }} = {{ .Values.options.memoryHighWatermark.value }}
    {{- end }}
