{{- $existingErlangCookie := "" }}
{{- $existingUser := "" }}
{{- $existingPassword := "" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "rabbitmq.fullname" .) ) }}
{{- if $secret }}
{{- $existingErlangCookie = index $secret.data "RABBITMQ_ERLANG_COOKIE" }}
{{- $existingUser = index $secret.data "RABBITMQ_DEFAULT_USER" }}
{{- $existingPassword = index $secret.data "RABBITMQ_DEFAULT_PASS" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_ERLANG_COOKIE: {{ (coalesce (.Values.authentication.erlangCookie | default "" | b64enc) $existingErlangCookie (randAlphaNum 32 | b64enc)) | quote }}
  RABBITMQ_DEFAULT_USER: {{ (coalesce (.Values.authentication.user | default "" | b64enc) $existingUser ("guest" | b64enc)) | quote }}
  RABBITMQ_DEFAULT_PASS: {{ (coalesce (.Values.authentication.password | default "" | b64enc) $existingPassword (randAlphaNum 10 | b64enc)) | quote }}
