apiVersion: v2
name: redis
description: A Helm chart for Redis on Kubernetes

type: application

maintainers:
  - name: groundhog2k

# This is the chart version
version: "0.7.1"

# This is the version number of the application being deployed.
appVersion: "7.2.1"
