apiVersion: v2
name: rabbitmq
description: A Helm chart for a RabbitMQ cluster on Kubernetes

type: application

maintainers:
  - name: groundhog2k
    url: https://github.com/groundhog2k/helm-charts

keywords:
  - messaging
  - rabbitmq

version: "2.0.7"

appVersion: "4.0.9"
icon: https://www.rabbitmq.com/img/rabbitmq-logo-with-name.svg
