apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-http
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    {{- with .Values.services.http.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.services.http.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
    - port: {{ .Values.services.http.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and ( or (eq .Values.services.http.type "LoadBalancer") (eq .Values.services.http.type "NodePort") ) (.Values.services.http.nodePort) }}
      nodePort: {{ .Values.services.http.nodePort }}
      {{- end }}
  {{- if and (eq .Values.services.http.type "LoadBalancer") (.Values.services.http.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.services.http.loadBalancerIP }}
  {{- end }}   
  {{- if and (eq .Values.services.http.type "LoadBalancer") (.Values.services.http.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges: {{- toYaml .Values.services.http.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}   
  {{- if (.Values.services.http.clusterIP) }}
  clusterIP: {{ .Values.services.http.clusterIP }}
  {{- end }}
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-ssh
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    {{- with .Values.services.ssh.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.services.ssh.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.ssh.type }}
  ports:
    - port: {{ .Values.services.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
      {{- if and ( or (eq .Values.services.ssh.type "LoadBalancer") (eq .Values.services.ssh.type "NodePort") ) (.Values.services.ssh.nodePort) }}
      nodePort: {{ .Values.services.ssh.nodePort }}
      {{- end }}
  {{- if and (eq .Values.services.ssh.type "LoadBalancer") (.Values.services.ssh.loadBalancerIP) }}
  loadBalancerIP: {{ .Values.services.ssh.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.services.ssh.type "LoadBalancer") (.Values.services.ssh.loadBalancerSourceRanges) }}
  loadBalancerSourceRanges: {{- toYaml .Values.services.ssh.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if (.Values.services.ssh.clusterIP) }}
  clusterIP: {{ .Values.services.ssh.clusterIP }}
  {{- end }}
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
